language: cpp
compiler: gcc


before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

script:
  - mkdir -p qt-creator-build
  - cd qt-creator-build
  - qmake ../qt-creator/qtcreator.pro
  - make all -j3