language: cpp
compiler: gcc


before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
  - sudo apt-get update -qq
  # - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

install:
  - sudo apt-get -qy install qt5-qmake qtbase5-dev

script:
  - mkdir -p qt-creator-build
  - cd qt-creator-build
  - whereis qmake
  - whereis qt5-qmake
  - qmake -v
  - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -v
  - /usr/lib/x86_64-linux-gnu/qt510/bin/qmake -v
  - qmake ../qt-creator/qtcreator.pro
  - make all -j3