language: cpp

git:
    submodules: false

os:
  - linux
  # - osx

dist: trusty

compiler:
  # - clang
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

env:
  matrix:
    - QT=510 BREW=@ex PPA=beineri/opt-qt-5.10.1-trusty

# addons:
#   coverity_scan:
#     project:
#       name: "pcolby/aws-sdk-qt"
#       description: "Build submitted via Travis CI"
#     notification_email: git@colby.id.au
#     build_command_prepend: >
#       cp -a "$TRAVIS_BUILD_DIR" "$TRAVIS_BUILD_DIR-scan" &&
#       pushd "$TRAVIS_BUILD_DIR-scan" &&
#       qmake -qt=qt5 -Wall -Wlogic -Wparser CONFIG+=debug_and_release
#     build_command: make all
#     branch_pattern: coverity

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-trusty
  - sudo apt-get -qy update
  # - eval "${MATRIX_EVAL}"
  # - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

install:
  # - sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns qt${QT}declarative
  - sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev
  - qmake -v



before_script:
  - export QMAKESPEC=linux-g++
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - mkdir -p qt-creator-build
  - cd qt-creator-build
  - qmake "CONFIG+=silent" ../qt-creator/qtcreator.pro

script:
  - make -j3
