language: cpp
compiler: gcc


before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -qy install qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt510/bin/qmake

script:
  - mkdir -p qt-creator-build
  - cd qt-creator-build
  - qmake ../qt-creator/qtcreator.pro
  - make all -j3