language: cpp

git:
    submodules: false

os:
  - linux
  # - osx

dist: trusty

compiler:
  # - clang
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-trusty
  - sudo apt-get -qy update
  - eval "${MATRIX_EVAL}"
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

install:
  - sudo apt-get -qy install qt510-meta-minimal


before_script:
  - '. /opt/qt510/bin/qt510-env.sh'
  - git clone https://code.qt.io/qt-creator/qt-creator.git
  - mkdir -p build-qtcreator-Desktop-Debug
  - cd build-qtcreator-Desktop-Debug
  - qmake "CONFIG+=silent" ../qt-creator/qtcreator.pro

script:
  - make -j7
  - cd ../
  - mkdir -p build-Desktop-CodeInsight-Debug
  - cd build-Desktop-CodeInsight-Debug
  - qmake "CONFIG+=silent" ../CodeInsight/codeinsight.pro
  - make -j7
